[package]
name = "pontoon"
version = "0.1.0"
authors = ["D. Ryan Hild <d.ryan.hild@gmail.com>"]
edition = "2018"

[workspace]
members = [
  "pontoon-client",
  "pontoon-core",
  "pontoon-server",
  "pontoon-storage",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "^0"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
tiny_http = "^0"
url = "^2"
http_req = "^0"
env_logger = "^0"
clap = { version = "^2", features = ["yaml"], optional = true }
crossbeam-channel = "^0"

[[bin]]
name = "raft"
path = "src/bin/raft.rs"
required-features = ["runtime"]

[features]
runtime = ["clap"]
